# Generated by Django 5.1.2 on 2024-10-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internet',
            old_name='twitter_name',
            new_name='twiiter_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('full stack developer', 'Full Stack Developer'), ('designer', 'Designer'), ('flater', 'Flater')], default='full stack developer', max_length=255),
        ),
    ]
