# Generated by Django 5.1.2 on 2024-10-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_twitter_name_internet_twiiter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='internet_id',
        ),
        migrations.DeleteModel(
            name='Internet',
        ),
    ]
