# Generated by Django 5.1.2 on 2024-10-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_user_internet_id_delete_internet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('website_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('twiiter_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('github_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('facebook_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
