# Generated by Django 5.1.2 on 2024-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_internet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_on',
            field=models.DateTimeField(default='2024-10-15'),
        ),
    ]
