# Generated by Django 5.1.2 on 2024-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_user_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
